### PR TITLE
Avoid a doc alias attribute error.

### PR DESCRIPTION
**Pull request by ratmice**
"error: doc alias attribute expects a string: #[doc(alias = "a")]"
This error can be seen in the tests at
https://github.com/rust-lang/rust/pull/72780

### CODE REVIEW

**Comment by koutheir** [comment]
Thank you for your efforts!

Do you see this error when building with a nightly toolchain?

**Comment by ratmice** [comment]
Nope, it was with 
```
$ rustc --version
rustc 1.51.0 (2fd73fabe 2021-03-23)
```

**Comment by koutheir** [comment]
So is this for compatibility with that version of Rust?

**Comment by ratmice** [comment]
Yes, I did a little bisecting rustup and it compiles as low as 1.48 now, but `cargo test` still requires a newer version though. Tests get ` or-patterns syntax is experimental`, but I saw this was from a recent commit for reducing the MSRV and figured it might reduce further.  I don't in particular have any issues doing an upgrade to a more recent compiler (So no harm if you want to close this and stay with where it is at).
```
error[E0710]: an unknown tool name found in scoped lint: `rustdoc::invalid_html_tags`
```

**Comment by koutheir** [comment]
Again, thank you for your investigation!

I simply wanted to get a clearer picture on what is going on. Your changes make sense to me.

**Comment by ratmice** [comment]
I believe i've fixed all the testsuite errors,
which were all in dev-dependencies: rsix, and unsafe-io depended on by socketpair.
Those have been merged and whenever they hit crates.io and socketpair upgrates hopefully testing will just work.

**Comment by koutheir** [comment]
I don't know which errors you're referring to. I updated the `socketpair` and published version `0.2.4` to [crates.io](https://crates.io/crates/selinux) 4 hours ago. See [this commit](https://github.com/koutheir/selinux/commit/1e4b5bf0a7d5b9a6f05075cc23adfbb1645df169). Tests build fine on Rust `1.55.0`.

**Comment by ratmice** [comment]
Sorry, could have explained better, as of this commit on Rust `1.51.0`, `cargo build` works, but `cargo test` still fails to compile tests, so while it compiles with `1.51` and `1.48`.  I haven't actually managed to test it with these compilers.

https://github.com/sunfishcode/unsafe-io/pull/10
https://github.com/bytecodealliance/rsix/pull/71

**Comment by koutheir** [comment]
I see your point. I didn't observe these errors, as I only build and test the latest stable.

The issue comes from a dependency, so I think it's reasonable to wait for them to fix this issue. If that is not fixed within a reasonable duration, then I might consider removing the dependency and reimplementing what I use from it (currently the `security_context_of_peer_socket` test), or forking and maintaining the dependency. Also, if compatibility with Rust `1.51.0` becomes a non-issue, then this problem also becomes out of scope. Let's wait and see.

If this problem is very important to you, then feel free to create a new issue about this crate's tests not building on Rust `1.51.0`, so you can track the issue.

**Comment by ratmice** [comment]
Not of any importance, I just wanted to document the current situation, since I may not, or probably won't notice once the crates are updated.
